### ISSUE TITLE
Questions about mexGetMatchingScore

### ISSUE THREAD

**Issue by cuibeibei-1990** [netw0rkf10w/ADGM#2]
As Readme told us:
## Installation
In Matlab, go to the folder ```ADGM/``` and run:
```
compile.m
```

But after I do this, there is a error: 
> Error compile (line 1)
> mex mexGetMatchingScore.cpp

If we ignore this, when we go back to the main folder and run: demo,
there will be a new error which still about mexGetMatchingScore

Error demo (line 52)
> [feat1,feat2] = mexComputeFeature(P1,P2,int32(t1),'simple');

So may be there are something wrong in the code of mexGetMatchingScore?

**Comment by netw0rkf10w** [comment]
@cuibeibei-1990 Could you post the complete output when running `compile.m`?

For running `demo.m`, you have to run 4 different `mex` commands first. Please refer to the [Demo](https://github.com/netw0rkf10w/adgm#demo) section for details.

**Comment by cuibeibei-1990** [comment]
1. Yes, of course, the complete output when running compile.m is as shown below:

Wrong usage mex
mexGetMatchingScore.cpp
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexGetMatchingScore.cpp(11): error C2664: 'double getMatchingScore(const double *,const int *,const double *,int)': cannot convert
argument 2 from 'mwSize *' to 'const int *'
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexGetMatchingScore.cpp(11): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style
cast

Error compile (line 1)
mex mexGetMatchingScore.cpp

2. And I have already run 4 different mex commands first as shown in Demo section, and there are no errors at the first 3 steps.But when I run the last step, " Go back to the main folder and run: demo", there are new errors as shown below:

Undefined function or variable 'mexGetMatchingScore'。

Error  getMatchingScore (line 2)
score = mexGetMatchingScore(X, int32(indH), valH);

Error  demo (line 80)
objective_TM = getMatchingScore(X_TM, indH, valH);

3. I have check the source code of mexGetMatchingScore, all of the code are:

function score = getMatchingScore(X, indH, valH)
score = mexGetMatchingScore(X, int32(indH), valH);

I don't know if they are all of the getMatchingScore, are there something missed in this function?

**Comment by netw0rkf10w** [comment]
I see. Your compiler was not able to do implicit conversion between `mwSize *`and `const int *`.

Unfortunately I don't have a Windows machine to test. Try modifying the content of `mexGetMatchingScore.h` to the following and run `compile.m` again:
```
/// D. Khuê Lê-Huu on October 19, 2016
double getMatchingScore(const double* X, const size_t* indH, const double* valH, size_t N)
{
    double score = 0.0;
    for(size_t i = 0; i < N; i++){
    	size_t i1 = indH[i];
    	size_t i2 = indH[i+N];
    	size_t i3 = indH[i+2*N];
    	if(X[i1] > 0 && X[i2] > 0 && X[i3] > 0)
        	score += valH[i]*X[i1]*X[i2]*X[i3];
        }
    return score;
}
```

Note that all `mex` commands have to be success before you can use `demo.m`.

**Comment by cuibeibei-1990** [comment]
I have tried as you said, but I am sorry there are still errors :

Wrong usage: mex
mexADGM_3rdORDER.cpp
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\eigen\eigen\src/Core/arch/CUDA/Half.h: warning C4819: The file contains a character that cannot be represented in the current code page
(936). Save the file in Unicode format to prevent data loss
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\condat_simplexproj.h: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the
file in Unicode format to prevent data loss
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\condat_simplexproj.h(437): warning C4018: '<': signed/unsigned mismatch
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\condat_simplexproj.h(488): warning C4018: '<': signed/unsigned mismatch
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\condat_simplexproj.h(504): warning C4018: '<': signed/unsigned mismatch
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\condat_simplexproj.h(510): warning C4018: '<': signed/unsigned mismatch
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\condat_simplexproj.h(528): warning C4018: '<': signed/unsigned mismatch
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\condat_simplexproj.h(543): warning C4018: '<': signed/unsigned mismatch
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\condat_simplexproj.h(567): warning C4018: '<': signed/unsigned mismatch
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\outils.h(154): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'unsigned int', possible loss of data
        with
        [
            Derived=Eigen::Matrix<double,-1,1,0,-1,1>
        ]
c:\users\cuibeibei\desktop\paper_with_code\adgm-master\adgm-master\adgm\outils.h(170): warning C4018: '<': signed/unsigned mismatch
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(21): warning C4101: 'tdims': unreferenced local variable
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(21): warning C4101: 'fdims': unreferenced local variable
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(51): warning C4244: 'initializing': conversion from 'double' to 'std::mwSize', possible loss of data
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(52): warning C4800: 'double': forcing value to bool 'true' or 'false' (performance warning)
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(53): warning C4800: 'double': forcing value to bool 'true' or 'false' (performance warning)
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(54): warning C4244: 'initializing': conversion from 'double' to 'std::mwSize', possible loss of data
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(55): warning C4244: 'initializing': conversion from 'double' to 'std::mwSize', possible loss of data
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(56): warning C4244: 'initializing': conversion from 'double' to 'std::mwSize', possible loss of data
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(75): error C2664: 'int ADGM_3rdORDER(double *&,double *&,double &,const double *,int,int,const int *,const double
*,int,const double *,int,int,bool,bool,int,int,int)': cannot convert argument 7 from 'mwSize *' to 'const int *'
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(75): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexADGM_3rdORDER.cpp(78): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data


Error  compile (line 3)
mex CXXFLAGS="\$CXXFLAGS -std=c++11" CXXOPTIMFLAGS='\$CXXOPTIMFLAGS -Ofast -DNDEBUG' -I"./Eigen"  mexADGM_3rdORDER.cpp

**Comment by netw0rkf10w** [comment]
Same problem. I'll push an update to the code tonight to fix this. If you can't wait then try replacing `int` with `size_t` in the code whenever you observe an error (try to read the error messages), like I did above with `mexGetMatchingScore.h`.

**Comment by netw0rkf10w** [comment]
I'm still having some strange bug after converting `int` to `size_t` in the code.

I think the best solution for you now is to use the original code in this repo without any modification (i.e. you should revert the changes I did to `mexGetMatchingScore.h` above), and **change** the C++ compiler.

Did you observe any warnings when running `mex`? Please post the complete Matlab output.

**Comment by cuibeibei-1990** [comment]
1.
(After I revert the changes in mexGetMatchingScore.h)
The first step that I do is to go to the folder ```ADGM/``` and run:   compile.m

All of the warnings and errors are below:

Wrong usage mex
mexGetMatchingScore.cpp
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexGetMatchingScore.cpp(11): error C2664: 'double getMatchingScore(const double *,const int *,const double *,int)': cannot convert
argument 2 from 'mwSize *' to 'const int *'
C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ADGM\mexGetMatchingScore.cpp(11): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style
cast


Error compile (line 1)
mex mexGetMatchingScore.cpp

2.
So my curious point is this problem came  due to :
a. The configuration of the computer is different ?
b. The version of matlab is different (I use R2019a) ?
c. Or because of the difference of the system (I use Windows system) ?

I think that's important to know.

Thanks.

**Comment by netw0rkf10w** [comment]
Could you post the complete Matlab output when running the 4 `mex` commands listed in the [Demo](https://github.com/netw0rkf10w/ADGM#demo) section?

**Comment by cuibeibei-1990** [comment]
1. In Matlab, go to ```ann_mwrapper/``` and run:
```
ann_compile_mex
```
RESULT:
-----------------------------------------------------------------
Copyright (c) Microsoft Corporation 2012. 

All rights reserved.


del "C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ann_mwrapper\private\ann_mex.exp" "C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ann_mwrapper\private\ann_mex.lib" "C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ann_mwrapper\private\ann_mex.mexw64.manifest" "C:\Users\cuibeibei\Desktop\paper_with_code\adgm-master\adgm-master\ann_mwrapper\private\ann_mex.ilk"
MEX has been successfully completed.。

-----------------------------------------------------------------

2. Go back to the main folder and run:
```
mex assignmentoptimal.cpp
```
RESULT:

-----------------------------------------------------------------
>> mex assignmentoptimal.cpp
Compile with 'Microsoft Visual C++ 2015'.
MEX has completed successfully.
-----------------------------------------------------------------


3. Go to ```TM/``` and run:
```
mex mexSource/mexComputeFeature.cpp -output mex/mexComputeFeature
mex mexSource/mexTensorMatching.cpp -output mex/mexTensorMatching
```

RESULT:
-----------------------------------------------------------------
>> mex mexSource/mexComputeFeature.cpp -output mex/mexComputeFeature
Mex mexSource/mexTensorMatching.cpp -output mex/mexTensorMatching
Compile with 'Microsoft Visual C++ 2015'.
MEX has completed successfully.
Compile with 'Microsoft Visual C++ 2015'.
MEX has completed successfully.
-----------------------------------------------------------------


4. Go back to the main folder and run:
```
demo
```

RESULT:
-----------------------------------------------------------------
>> demo
Undefined function or variable 'mexGetMatchingScore'.

Error getMatchingScore (line 2)
Score = mexGetMatchingScore(X, int32(indH), valH);

Error demo (line 80)
objective_TM = getMatchingScore(X_TM, indH, valH);
-----------------------------------------------------------------

**Comment by netw0rkf10w** [comment]
I have updated the code. Please download it and try again.

**Comment by cuibeibei-1990** [comment]
Yes, thanks for your update, it can run very well, thanks a lot!

**Comment by netw0rkf10w** [comment]
You are welcome! Looking forward to reading your publications ;) Good luck!
